# -*- coding: utf-8 -*-
"""Submission 2 - Sistem Rekomendasi Destinasi Wisata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zh0HBHLU5Vb49xU3Fr8myaWS5vRSnKEQ

# Install dan Import Library
"""

!pip install numpy==1.24.4 --force-reinstall

!pip install scikit-surprise

# Import Library
import kagglehub
import pandas as pd
import os
import random
import operator
import requests
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import sparse
import sys
from surprise import Dataset, Reader, accuracy, NMF, SlopeOne, CoClustering
from surprise.model_selection import train_test_split, GridSearchCV
from surprise.dataset import DatasetAutoFolds
from collections import defaultdict

"""Install dan Import library ini sengaja dikelompokan untuk mengetahui apa saja yang dibutuhkan dalam project ini.

# Data Understanding
"""

# Download latest version
path = kagglehub.dataset_download("aprabowo/indonesia-tourism-destination")

datafile = os.listdir(path)
datafile

"""Mengunduh dataset yang akan digunakan pada project. Adapun datasetnya berasal dari Kaggle yang bernama [Indonesia Tourism Destination](https://www.kaggle.com/datasets/aprabowo/indonesia-tourism-destination)"""

places = pd.read_csv(path + '/tourism_with_id.csv')
ratings = pd.read_csv(path + '/tourism_rating.csv')

print("Jumlah Profil Pengguna: ", len(ratings.User_Id.unique()))
print("Jumlah Tempat Wisata: ", len(places))
print("Jumlah Rating : ", len(ratings))
print("Jumlah Pengguna yang memberikan Rating: ", len(ratings.User_Id.unique()))
print("Jumlah Tempat Wisata yang mendapatkan Rating: ", len(ratings.Place_Id.unique()))

"""Mengambil informasi umum yang tersedia dalam dataset, seperti jumlah baris yang tersedia dan jumlah wisata di Indonesia yang terdapat pada dataset.

# Univariate Exploratory Data Analysis

## Variabel rating
"""

ratings.head(5)

"""Mengambil sampel data pada variabel ratings."""

ratings.info()

"""Fungsi ini digunakan untuk melihat informasi setiap kolom dalam dataset termasuk jumlah baris pada dataset dan tipe data dari setiap kolomnya."""

ratings.describe()

"""Berdasarkan statistik deskriptif diatas, didapat bahwa :
*   Jumlah rating yang diberikan kepada 437 tempat wisata berjumlah 10.000
*   Rating yang digunakan memiliki skala 1 - 5.

## Variabel places
"""

places.head(5)

"""Mengambil sampel data pada variabel ratings."""

places.info()

print("\nList Tempat Wisata: ", places.Place_Name.unique())

"""Fungsi ini digunakan untuk melihat informasi umum pada variabel places sekaligus menampilkan destinasi wisata yang masuk dalam dataset."""

places['City'].value_counts()

"""Statistik ini menunjukan sebaran destinasi wisata pada setiap kota besar di Indonesia."""

# Buat subplots dengan 1 baris dan 2 kolom
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# --- Grafik 1: Sebaran Destinasi Wisata Berdasarkan Kota ---
sns.countplot(
    x='City',
    data=places,
    order=places['City'].value_counts().index,
    ax=axes[0]
)
axes[0].set_title('Sebaran Destinasi Wisata Berdasarkan Kota')
axes[0].set_xlabel('Kota Destinasi Wisata')
axes[0].set_ylabel('Jumlah Destinasi Wisata')
axes[0].tick_params(axis='x', rotation=90)

# --- Grafik 2: Sebaran Destinasi Wisata Berdasarkan Kategori ---
# Urutkan usia secara numerik
sns.countplot(
    x='Category',
    data=places,
    order=places['Category'].value_counts().index,
    ax=axes[1]
)
axes[1].set_title('Sebaran Destinasi Wisata Berdasarkan Kategori')
axes[1].set_xlabel('Kategori')
axes[1].set_ylabel('Jumlah Destinasi Wisata')

# Tampilkan kedua grafik
plt.tight_layout()
# Simpan Grafik
plt.savefig('sebaran_destinasi.png', dpi=300, bbox_inches='tight')

plt.show()

"""Grafik ini merupakan sebaran destinasi wisata berdasarkan kota dan kategorinya. Terlihat data tidak seimbang dari setiap kotanya maupun dari setiap kategorinya.

# Data Preprocessing
"""

reader = Reader(rating_scale=(1,5)) # rating scale range
data = Dataset.load_from_df(ratings[['User_Id', 'Place_Id', 'Place_Ratings']], reader)

"""Fungsi ini digunakan untuk menyiapkan data rating pengguna terhadap tempat agar bisa digunakan dalam algoritma sistem rekomendasi menggunakan library Surprise. Jadi artinya format dataset sebelumnya diubah menjadi format dataset internal Surprise."""

# Split the data into training and testing sets
trainset, testset = train_test_split(data, test_size=0.3)

"""Membagi dataset menjadi train set dan test set dengan proporsi 70% untuk train set dan 30% untuk test set.

# Model Development

## Inisialisasi model menggunakan algoritma Slope One
"""

# Membuat model Slope One
model_slope_one = SlopeOne()

# Melatih model Slope One pada data training
model_slope_one.fit(trainset)

"""Melatih model menggunakan Algoritma Slope One

## Inisialisasi model menggunakan algoritma NMF
"""

# Define parameter grid untuk mode
param_grid = {
     'n_factors': [10, 20, 50, 100],
    'n_epochs': [20, 50, 100],
    'reg_pu': [0.02, 0.05, 0.001],
    'reg_qi': [0.02, 0.05, 0.001]
}

# Grid search untuk NMF
gs_nmf = GridSearchCV(NMF, param_grid, measures=['rmse', 'mae'], cv=5, joblib_verbose=1)
gs_nmf.fit(data)

# Lihat hasil terbaik
print("Best RMSE Score:", gs_nmf.best_score['rmse'])
print("Best Params:", gs_nmf.best_params['rmse'])

# Model terbaik
best_model = gs_nmf.best_estimator['rmse']

"""Kode ini menjalankan Grid Search Cross Validation untuk menemukan parameter terbaik dari algoritma rekomendasi NMF menggunakan library Surprise. Tujuannya adalah untuk mengoptimalkan performa model rekomendasi berdasarkan metrik error seperti RMSE (Root Mean Squared Error) dan MAE (Mean Absolute Error). Hasil dari Grid Search ini nantinya digunakan sebagai parameter dalam melatih model NMF."""

# Use the SVD algorithm to train the model
model_NMF = NMF(n_factors=100, n_epochs=50, reg_pu=0.05, reg_qi=0.05)
model_NMF.fit(trainset)

"""Melatih model dengan algoritma NMF yang tersedia pada library Surprise dengan paramater terbaik.

## Inisialisasi model menggunakan algoritma Co Clustering
"""

# Definisikan parameter grid untuk Co-Clustering
param_grid_co_clustering = {
    'n_cltr_u': [1, 3, 5, 10],
    'n_cltr_i': [1, 3, 5, 10],
    'n_epochs': [10, 20, 50]
}

# Melakukan Grid Search untuk Co-Clustering
gs_co_clustering = GridSearchCV(CoClustering, param_grid_co_clustering, measures=['rmse', 'mae'], cv=5)
gs_co_clustering.fit(data)

# Mendapatkan model terbaik dan parameter terbaik untuk Co-Clustering
best_co_clustering_model = gs_co_clustering.best_estimator['rmse']
best_co_clustering_params = gs_co_clustering.best_params['rmse']

print("Best Params for Co-Clustering:", best_co_clustering_params)
print("Best RMSE for Co-Clustering:", gs_co_clustering.best_score['rmse'])

"""Kode ini menjalankan Grid Search Cross Validation untuk menemukan parameter terbaik dari algoritma rekomendasi Co Clustering menggunakan library Surprise. Tujuannya adalah untuk mengoptimalkan performa model rekomendasi berdasarkan metrik error seperti RMSE (Root Mean Squared Error) dan MAE (Mean Absolute Error). Hasil dari Grid Search ini nantinya digunakan sebagai parameter dalam melatih model Co Clustering."""

model_co_clustering = CoClustering(n_cltr_u=1, n_cltr_i=1, n_epochs=10)
model_co_clustering.fit(trainset)

"""Melatih model dengan menggunakan Algoritma Co Clustering

# Model Evaluasi
"""

metrics = pd.DataFrame(columns=['Test_RMSE','Test_MAE', 'Precision@10', 'Recall@10'], index=['Slope_One', 'NMF', 'Co_Clustering'])

model_dict = {'Slope_One': model_slope_one, 'NMF': model_NMF, 'Co_Clustering': model_co_clustering}

"""Menginisialisasi dataframe metrics untuk menampung nilai dari metrics evaluasi sekaligus menyimpan model yang telah dilatih."""

def precision_recall_at_k(predictions, k=5, threshold=4.0):
    user_est_true = defaultdict(list)

    for uid, _, true_r, est, _ in predictions:
        user_est_true[uid].append((est, true_r))

    precisions = {}
    recalls = {}

    for uid, user_ratings in user_est_true.items():
        # Urutkan berdasarkan rating prediksi (descending)
        user_ratings.sort(key=lambda x: x[0], reverse=True)

        # Hitung total item relevan (berdasarkan true_r)
        n_rel = sum((true_r >= threshold) for (_, true_r) in user_ratings)

        # Hitung item relevan dalam top-k (berdasarkan true_r)
        n_rec_k = sum((true_r >= threshold) for (_, true_r) in user_ratings[:k])

        # Precision@k: proporsi relevan dalam top-k
        precisions[uid] = n_rec_k / k

        # Recall@k: proporsi item relevan yang tercover
        recalls[uid] = n_rec_k / n_rel if n_rel != 0 else 0

    # Rata-rata semua user
    avg_precision = sum(precisions.values()) / len(precisions)
    avg_recall = sum(recalls.values()) / len(recalls)

    return avg_precision, avg_recall

"""Fungsi untuk menghitung precision@k dan recall@k"""

for name, model in model_dict.items():
    # Melakukan prediksi pada data test
    pred_test = model.test(testset)
    precision, recall = precision_recall_at_k(pred_test, k=10, threshold=4)

    # Menghitung RMSE dan MAE
    metrics.loc[name, 'Test_RMSE'] = accuracy.rmse(pred_test, verbose=False)
    metrics.loc[name, 'Test_MAE'] = accuracy.mae(pred_test, verbose=False)
    metrics.loc[name, 'Precision@10'] = precision
    metrics.loc[name, 'Recall@10'] = recall

metrics

"""Melakukan testing model sekaligus menghitung metrics evaluasi untuk RMSE, MAE, Precision@k dan Recall@k, yang kemudian disimpan dalam dataframe metrics.

# Inferensi Model
"""

def get_top_highest_rated_places(user_id):
    user_place_ids = ratings[ratings['User_Id'] == user_id]

    highest_rated_places = user_place_ids.merge(places[['Place_Id', 'Place_Name', 'Category']], on='Place_Id').sort_values(by='Place_Ratings', ascending=False).head(5)
    print('Showing recommendations for users: {}'.format(user_id))
    print('====' * 9)
    print('Destination with high ratings from user')
    print('----' * 8)
    for row in highest_rated_places.itertuples():
        print(row.Place_Id, ':', row.Place_Name, ':', row.Category)

"""Fungsi diatas untuk mengambil rating tertinggi yang diberikan pengguna terhadap destinasi wisata. Daftar tersebut diambil sebagai acuan untuk membandingkan antara destinasi yang relevan dengan destinasi yang direkomendasikan."""

def get_top_n_recommendations(name, model, user_id, n=10):
    # Dapatkan semua item yang belum di-rating oleh user
    testset = trainset.build_anti_testset()
    testset = filter(lambda x: x[0] == user_id, testset)

    # Prediksi rating untuk semua item
    predictions = model.test(testset)

    # Urutkan prediksi berdasarkan rating tertinggi
    predictions.sort(key=lambda x: x.est, reverse=True)

    # Ambil top N rekomendasi
    top_n = predictions[:n]

    # Konversi ke DataFrame
    recommendations_df = pd.DataFrame([{
        'Place_Id': pred.iid,
    } for pred in top_n])

    recommendations_df = recommendations_df.merge(places[['Place_Id', 'Place_Name', 'Category']], on='Place_Id')
    print('----' * 8)
    print('Top 10 Rekomendasi menggunakan Model', name)
    print('----' * 8)
    for row in recommendations_df.itertuples():
        print(row.Place_Id, ':', row.Place_Name, ':', row.Category)

"""fungsi diatas untuk mengambil Top 10 rekomendasi  destinasi wisata berdasarkan User_Id."""

user_id = 211
get_top_highest_rated_places(user_id)
for name, model in model_dict.items():
  get_top_n_recommendations(name, model, user_id)